
CREATE TABLE GRAFOS (
    ID      NUMBER GENERATED ALWAYS AS IDENTITY, 
    NOMBRE  VARCHAR2(100) NOT NULL, 
    CONSTRAINT "GRAFO_PK" PRIMARY KEY (ID)
);
/

CREATE TABLE NODOS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
    NOMBRE      VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
    GRAFO_ID    NUMBER NOT NULL ENABLE, 
    COLOR       VARCHAR2(100) COLLATE "USING_NLS_COMP", 
    GRADO       NUMBER, 
    GRADO_ERROR NUMBER, 
    CONSTRAINT "NODO_PK" PRIMARY KEY (ID)
);

ALTER TABLE NODOS ADD CONSTRAINT "NODO_GRAFO_FK" FOREIGN KEY (GRAFO_ID) REFERENCES GRAFOS (ID);
/

CREATE TABLE ARISTAS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
    GRAFO_ID    NUMBER NOT NULL ENABLE, 
    FROM_NODE   NUMBER NOT NULL ENABLE, 
    TO_NODE     NUMBER NOT NULL ENABLE, 
    PESO        NUMBER DEFAULT 0, 
    CONSTRAINT "ARISTA_PK" PRIMARY KEY (ID)
);

ALTER TABLE ARISTAS ADD CONSTRAINT ARISTA_GRAFO_FK FOREIGN KEY (GRAFO_ID) REFERENCES GRAFOS (ID);

ALTER TABLE ARISTAS ADD CONSTRAINT ARISTA_FROM_FK FOREIGN KEY (FROM_NODE) REFERENCES NODOS (ID);

ALTER TABLE ARISTAS ADD CONSTRAINT ARISTA_TO_FK FOREIGN KEY (TO_NODE) REFERENCES NODOS (ID);
/

CREATE TABLE GRAFO_COLORES(
    ID  NUMBER GENERATED ALWAYS AS IDENTITY,
    COLOR   VARCHAR2(10) NOT NULL,
    NOMBRE  VARCHAR2(20) NOT NULL,
    CONSTRAINT "COLOR_PK" PRIMARY KEY (ID)
);
/